# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl)

from . import (
    organization_arrondissement,
    organization_commentaire,
    organization_demande_adhesion,
    organization_demande_service,
    organization_droits_admin,
    organization_echange_service,
    organization_fichier,
    organization_membre,
    organization_occupation,
    organization_offre_service,
    organization_organization,
    organization_origine,
    organization_point_service,
    organization_provenance,
    organization_quartier,
    organization_region,
    organization_revenu_familial,
    organization_situation_maison,
    organization_type_communication,
    organization_type_compte,
    organization_type_fichier,
    organization_type_service,
    organization_type_service_categorie,
    organization_type_service_sous_categorie,
    organization_type_telephone,
    organization_ville,
)
