{
    "name": "Demo Mariadb Sql Example 1",
    "category": "Uncategorized",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "application": True,
    "depends": ["portal"],
    "data": [
        "security/ir.model.access.csv",
        "views/organization_arrondissement.xml",
        "views/demo_mariadb_sql_example_1_templates.xml",
        "views/organization_commentaire.xml",
        "views/organization_demande_adhesion.xml",
        "views/organization_demande_service.xml",
        "views/organization_droits_admin.xml",
        "views/organization_echange_service.xml",
        "views/organization_fichier.xml",
        "views/organization_membre.xml",
        "views/organization_occupation.xml",
        "views/organization_offre_service.xml",
        "views/organization_organization.xml",
        "views/organization_origine.xml",
        "views/organization_point_service.xml",
        "views/organization_provenance.xml",
        "views/organization_quartier.xml",
        "views/organization_region.xml",
        "views/organization_revenu_familial.xml",
        "views/organization_situation_maison.xml",
        "views/organization_type_communication.xml",
        "views/organization_type_compte.xml",
        "views/organization_type_fichier.xml",
        "views/organization_type_service.xml",
        "views/organization_type_service_categorie.xml",
        "views/organization_type_service_sous_categorie.xml",
        "views/organization_type_telephone.xml",
        "views/organization_ville.xml",
        "views/menu.xml",
    ],
    "installable": True,
}
